debate_group: "neutral_republican"  # options: "neutral_republican", "neutral_democrat", "neutral_republican_democrat"
debate_structure: "structured"  # options: "structured" (via taxonomy), "unstructured"


### for taxonomy ###
taxonomy_rounds: 1
taxonomy_iterations: 1
taxonomy_tree_depth: null  # options: 1, 2, 3, null = "unspecified"


### for debate ###
debate_rounds: 1
debate_iterations: 1
debate_structures: [["taxonomic", "full_tree"]]
# ["taxonomic", "full_tree"]
# ["taxonomic", "traversal"]
# ["non_taxonomic"]


baseline_debate_topics:
  - "illegal immigration"
  - "gun violence"
  - "abortion"
  - "climate change"

baseline_debate_questions:
- "Do Immigrants Take Jobs From American-Born Workers?"
- "Should there be stricter gun ownership laws?"
- "Should partial birth abortions be banned to protect unborn children?"
- "Should the city go ahead with building the manufacturing plant?"

# debate_motion = "The US should take stronger measures to combat climate change."

extra_debate_topics:
  - "racism"
  - "evolution"
  - "trade tariffs"


### for agents ###
token_limit: 75
temperature: 0.3
debate_agents:
  - identifier: "neutral"
    name: "Sam"
    model: "gemini-2.0-flash-lite" #"llama3.2:3b", "gemini-1.5-flash"
    party: null
    leaning: null

  - identifier: "republican"
    name: "Alex"
    model: "gemini-2.0-flash-lite"
    party: "Republican"
    leaning: "right-leaning"

  - identifier: "democrat"
    name: "Taylor"
    model: "gemini-2.0-flash-lite"
    party: "Democrat"
    leaning: "left-leaning"
