debate_group: "neutral_republican_democrat"  # options: "neutral_republican", "neutral_democrat", "neutral_republican_democrat"

### for taxonomy ###
taxonomy_rounds: 5
taxonomy_iterations: 1
taxonomy_tree_depth: null  # options: 1, 2, 3, null = "unspecified"


### for debate ###
debate_rounds: 20
debate_iterations: 10
debate_structures: 
  - "non_taxonomic"
  - "taxonomic_full_tree"
  - "taxonomic_traversal"


baseline_debate_topics:
  - "illegal immigration"
  - "gun violence"
  - "abortion"
  - "economy"

baseline_debate_questions:
- "Do immigrants take jobs away from American-born workers?"
- "Should the government enforce stricter gun ownership laws?"
- "Should partial-birth abortions be banned to protect unborn children?"
- "Should Congress raise taxes on the wealthy to reduce the federal budget deficit?"


extra_debate_topics:
  - "evolution"
  - "trade tariffs"
  - "climate change"

# - "Should the city go ahead with building the manufacturing plant?"

### for agents ###
token_limit: 75
temperature: 0.3
debate_agents:
  - identifier: "neutral"
    name: "Sam"
    model: "gemini-2.0-flash-lite" #"llama3.2:3b", "gemini-1.5-flash"
    party: null
    leaning: null

  - identifier: "republican"
    name: "Alex"
    model: "gemini-2.0-flash-lite"
    party: "Republican"
    leaning: "right-leaning"

  - identifier: "democrat"
    name: "Taylor"
    model: "gemini-2.0-flash-lite"
    party: "Democrat"
    leaning: "left-leaning"
